###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"George Mendel",
    "age":81,
    "email":"georgemendel@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/663044c4d4d3c5e3a1311bd1 HTTP/1.1

###
PUT http://localhost:9000/api/users/6630490bf2924d4566b86cdb HTTP/1.1
Content-Type: application/json

{
    "name":"George Mendeaasdal",
    "age":81,
    "email":"georgemendel@gmail.com"
}

###
DELETE http://localhost:9000/api/users/663048ebf2924d4566b86cd9 HTTP/1.1

